steps:
  # ==========================================
  # 1. BUILD & DEPLOY FASTAPI BACKEND
  # ==========================================
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/speedtest-backend', '-f', 'Dockerfile.backend', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/speedtest-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'speedtest-backend'
      - '--image=gcr.io/$PROJECT_ID/speedtest-backend'
      - '--set-env-vars=GCS_BUCKET_NAME=speedtest-artifacts-bucket'
      - '--region=asia-southeast1'
      - '--allow-unauthenticated'

  # ==========================================
  # 2. BUILD & DEPLOY STREAMLIT FRONTEND
  # ==========================================
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/speedtest-ui', '-f', 'Dockerfile.frontend', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/speedtest-ui']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'speedtest-ui'
      - '--image=gcr.io/$PROJECT_ID/speedtest-ui'
      - '--port=8501'
      - '--set-env-vars=BACKEND_URL=https://speedtestai-git-349863046910.asia-southeast1.run.app'
      - '--region=asia-southeast1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/speedtest-backend'
  - 'gcr.io/$PROJECT_ID/speedtest-ui'

# ✅ ป้องกัน Error เรื่อง Service Account logs
options:
  logging: CLOUD_LOGGING_ONLY