services:
  fastapi-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: k6-backend
    environment:
    - TZ=Asia/Bangkok
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - scripts_data:/app/scripts
      - summaries_data:/app/summaries
      - reviews_data:/app/reviews

  streamlit-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: k6-frontend
    ports:
      - "8501:8501"
    environment:
      # ✅ เหลือไว้เฉพาะ Base URL (ไม่มี /run-test ต่อท้าย)
      - BACKEND_URL=https://speedtest-backend-349863046910.asia-southeast1.run.app
    depends_on:
      - fastapi-backend
# ประกาศ Named Volumes ให้ Docker สร้างและจัดการพื้นที่ให้
volumes:
  scripts_data:
  summaries_data:
  reviews_data:
      